# Generated by Django 3.2.2 on 2021-05-08 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='assets',
            field=models.ManyToManyField(blank=True, to='wallet.Asset'),
        ),
    ]
